### ISSUE TITLE
Cambridge Hackathon 25th of April

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-events#1]
**What is the event?**
The hackathon will be held on the 25th of April by the Cambridge Blockchain Society. Due to their reach in Cambridge and them hosting the Hackathon at the Bradfield centre (a research institute) several of the participants are PhD candidates. Last year, 40% to 50% of participants were CS students. In a team of 4, there was about one student from Cambridge. Teams can form by students but the event is also open to the public. 

**When is the event?**
25th of April, 24h long

**Describe how you'd like NEAR to ideally participate**
The plan is that they collaborate with 2 crypto projects, one Layer one and one application layer project. Meaning, if Near gets involved as a sponsor, providing workshops and hackathon support, we would have direct reach to developers at the hackathon without other projects taking up participants' attention. The sponsorship package will be forwarded the following days. 

**Describe alternatives you'd be open to**
Not really an alternative since they only partner with 2 projects. 

**Describe what the goal of the event is**
If up to 50% of participants build on NEAR we would already have a direct reach to 100 participants. This will provide us with valuable devx feedback that we cannot get over online conversations. Besides, it would allow us to use the event as a case study to get involved in events with other Universities and meetup groups in the UK. 

**Additional Context**
Given that the event is close to the Future of Blockchain Hackathon Conference on the 27th of April in London (Cambridge and London are just 1h train ride apart), the two events can be combined without additional travel. Additionally, Near could host NEAR-only meetups with London-based meetup groups that we have been in contact with. 

**Contact**
Direct message on Slack, Telegram or Discord

**Timeline**
Need to reach a decision within the next two weeks:)

**Comment by AnaisUrlichs** [comment]
Received the sponsorship package and followed up with additional questions.

**Comment by ashleynear** [comment]
@AnaisUrlichs can you please attach the sponsorship package?

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sample](https://trello.com/c/imLJepPj/3-sample)

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cambridge Hackathon 25th of April #1](https://trello.com/c/imLJepPj/3-sample)

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cambridge Hackathon 25th of April #1](https://trello.com/c/imLJepPj/3-cambridge-hackathon-25th-of-april-1)

**Comment by AnaisUrlichs** [comment]
Shared on Slack, not sure how comfortable they feel about publishing it here :D

**Comment by ashleynear** [comment]
@AnaisUrlichs Struggling to find information about this event online; is there a link somewhere?

**Comment by ashleynear** [comment]
> Basic information for the event's consideration.


**What is the event called?**

CBHACK | Cambridge Bradfield Hackathon

**Who is the event for?**
100 hackers, students from Cambridge, Oxford, UCL, LSE and other top universities across the UK

**When is the event happening?**
25th -26 of April

**How is the event structured**
A Hackathon with places for booths, & workshops/tech talks

**What type of event is it?**
Hackathon | Sponsor | Attend

**How much would it cost?**
2K Base Sponsorship + 1K minimum travel lodging

**Goals for the event**
- Be one of two layer 1/blockchain protocols at the event & convert 50% to build on us
- Experiment with the student market (what can we gain? is there anything to gain?)
- Convert builders into long term builders who retain and stay building on NEAR (1% of all attendees)
- Gain the contact info for all attendees

**How much is a base ticket?**
N/A

**Have we attended before?**
No.

**Comment by ashleynear** [comment]
NEAR wants to do this event to experiment with the student market and determine if we can convert students from a hackathon into people who are continuously building or validating on NEAR.

We believe we can learn from this experiment, based on the fact that we would be one of two protocols present at the hackathon, (aka a captive audience hackathon) thus giving us valuable insight into the student market and it's potential for NEAR.


@AnaisUrlichs @eriktrautman would y'all agree with this?


Additionally, @AnaisUrlichs do you know if we would have all information of attendees at least one week prior? Is that an option?

**Comment by ashleynear** [comment]
@alexbreines <-- add comment here

**Comment by alexbreines** [comment]
Part of the consideration for University / Student Hackathon participation includes the goals of:

>>>>  Saturating mindshare of students in blockchain programs at universities, including but not limited to: Standford, UCLA, Oxford, Cambridge, NYU, Cornell, MIT, Carnegie Mellon, Princeton, Harvard, UPenn, Johns Hopkins, Duke, etc. We want these students to 1) Hack / Build on NEAR   2) Tell their friends about NEAR  3) Write their theses on NEAR  4) Consider contributing to or working with NEAR
>>>>  Capturing mindshare and attention of professors at universities with blockchain programs with the goal they eventually write academic papers that include NEAR.

**Comment by alexbreines** [comment]
@frol  Will you be in Europe this week? We'd love to have a technical nearkat on the ground for this to answer questions. If you won't be on that side of the globe, do you know another dev who might be?

**Comment by frol** [comment]
@alexbreines I am still in Buenos Aires, and I don't have a visa to go to UK. @fckt and @k06a are in Moscow (they also need UK visa, but they may have one).

**Comment by AnaisUrlichs** [comment]
@alexbreines there are going to be several PhD students; I think the best way to incentivise them to look at NEAR for their research is at those events.
Part of the University Ambassador program is to provide thesis support
