### ISSUE TITLE
[Event Proposal] Online Hackathon with Gitcoin

### ISSUE THREAD

**Issue by ceresstation** [nearprotocol/near-events#12]
What is the event?
An online hackathon using Gitcoin, over at least two weeks, with a global pool of hackers.

When is the event?
We have events happening from March through to May planned so far.

Who are the attendees and how many are expected?
We expect this to be in the hundreds. Between 500-900 applicants per event.

Describe how you'd like NEAR to ideally participate
Gitcoin would handle all operational overhead except for specifying prizes and providing product / technical support to hackers.

Describe alternatives you'd be open to
We want NEAR to make the best choice for their particular needs, but feel that Devpost is insufficient - especially without the additional marketing support Devpost provides for a relatively high cost - for building strong bridges between NEAR and other adjacent communities such as Ethereum, which we believe can learn from and build on each other's successes.

Describe what the goal of the event is

- Primary goal of the event is to get a large group of people to try to build on us, source complaints and sticking points in the developer experience and then fix them.
- Secondary goal is to showcase a bunch of projects that finish on a landing page for examples and demos by the end of the hackathon.
- Tertiary goal of the event is to meet great engineers who would be interested in working on other projects built on NEAR long term.

**Comment by ashleynear** [comment]
@ceresstation We'll need more info on the individual hackathons. (I know we discussed, just posting here for transparency)

**Comment by ashleynear** [comment]
Moving forward with processing individual hackathons, closing this ticket, but adding in the others
