### ISSUE TITLE
[June 8-10 2020] [London] CogX Web 3.0 Forum by Fabric Ventures

### ISSUE THREAD

**Issue by eriktrautman** [nearprotocol/near-events#17]
**What is the event?**
This will be the third edition of Fabric Web 3.0 Forum at CogX, and will be the biggest to date: CogX expects over 30,000 attendees, and Fabric expects at least 10,000 visitors to our 500-person stage over the 3 days. This is the biggest Web 3.0 event in Europe.

CogX will have close to 1000 speakers - from successful founders to corporate executives (e.g. CEO of Mastercard), to researchers, developers, asset managers & investors.

**Where is the event?**
Kings Cross, London.

**When is the event?**
It's a 3-day event June 8-10 (Monday-Wednesday)

**Who are the attendees and how many are expected?**
See above. More of a conference than a dev-focused thing.

**Describe how you'd like NEAR to ideally participate**
Giving a main stage talk and doing lots of private meetings/dinners around it to catch up with key people across the web3 space.

**Describe alternatives you'd be open to**
N/A

**Describe what the goal of the event is**
To get a strong exposure on a main stage where we can drop a big announcement.

**Additional Context**
Fabric, who put on the conference, are backers of NEAR

**Contact**
Anastasiya at Fabric

**Comment by ashleynear** [comment]
@eriktrautman do we have a speaking slot already confirmed?

**Comment by eriktrautman** [comment]
It's offered but unconfirmed. Working on it.

□-□-□
Erik S. Trautman
CEO, NEAR Foundation
Learn about the NEAR Protocol
<https://nearprotocol.com/blog/the-beginners-guide-to-the-near-blockchain/>
Writing <https://www.eriktrautman.com/>   | LinkedIn
<https://www.linkedin.com/in/erik-trautman/>   | Twitter
<https://twitter.com/ErikTrautman>
