### ISSUE TITLE
Blocklab Hackathon in Stuttgart Germany from the 17th to the 18th of April

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-events#2]
**What is the event?**
A yearly hackathon organised by Blocklab with several industry partners (Daimler, BMW, Bosch etc.). The industry partners provide challenges to participants. NEAR would have the option to get involved as Layer 1 and allow projects that build e.g. for Daimler on NEAR to qualify for multiple rewards. In that case, all teams would be incentivised to build on NEAR. While participants are likely to choose protocols they already have experience with, we would be the only layer one providing direct tech support at the hackathon.
The expected number of attendees is between 200 and 250. About 1/3 of participants are developers. The sponsorship package can be discussed but formally lies between 5k and 7k, depending on the number of workshops we want to hold.
Anton form Near, who attended and won the hackathon last year had a good experience and would recommend it. Participants are largely from Europe and Eastern Europe.

**When is the event?**
From the 17th to the 19th of April, 48h long

**Describe how you'd like NEAR to ideally participate**
We can get involved as sponsor, providing workshops, tech support to participants, and prizes for the top 3 projects building on NEAR. 

**Describe alternatives you'd be open to**
There are not many hackathons with similar reach and without additional Layer 1 projects. 

**Describe what the goal of the event is**
Build up a direct reach to developers. The goal would be that the majority of projects build on NEAR.

**Additional Context**
Can forward sponsorship documents, which are written partially in German.

Got put in touch with Blocklabs via a contributor, who is hosting events in Stuttgart for NEAR; the event would provide a great case study to onboard new contributors, connect with and expand our community in Germany.

This event could be held with several other events in Berlin before the events in London. 

**Contact**
Discord, Telegram, Commonwealth or Slack

**Timeline**
They need a response within the next week. Also, the DevX team would need some time to be able to prepare for larger hackathons.

**Comment by ashleynear** [comment]
@AnaisUrlichs this looks interesting. What would the 5K sponsorship entail? 

As a member of the DevEx team, do you know if we have enough time to prepare for this?

**Comment by ashleynear** [comment]
@AnaisUrlichs can you also please attach the sponsorship details?

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #2: Blocklab Hackathon in Stuttgart Germany from the 17th to the 18th of April](https://trello.com/c/ZQrwLJ1j/7-issue-2-blocklab-hackathon-in-stuttgart-germany-from-the-17th-to-the-18th-of-april)

**Comment by AnaisUrlichs** [comment]
In terms of timeline, they have to get a response this week. 
I would say we have the capacity in the devx team -- a hackathon is largely contributing to our goals if we receive developer feedback. However, I feel more comfortable cross-checking with the devx team. 

5k would entail
* NEAR participating in the hackathon as potential solution to build on 
* Seminar
* A separate room to give workshops
* A booth to showcase our project/business
* Contacts to businesses in the area (e.g. BMW, Bosch, Daimler etc.)
* Mentoring (as in us mentoring) 
Note that this is rough summary since the document is written in German

**Comment by ashleynear** [comment]
This is probably too much of a dispersion across Europe. Let's focus on London and Berlin for now.
