### ISSUE TITLE
[Event Date] DeFi Discussion

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-events#23]
**What is the event?**
Online DeFi Discussion conference

**Where is the event?**
Online

**When is the event?**
May 1st-3rd

**Who are the attendees and how many are expected?**
Previous conference had mostly developers as it was on Proof of Stake.
This time it's expected more diverse but still pretty technical

Previous "Proof of Stake Validator Summit"  had: 1.7 registrations / ~800 attendees, with 90-200 viewers per talk. (Had in person watch parties around the world)

**Describe how you'd like NEAR to ideally participate**
Sponsor 5k & give a talk 20m talk w/ 5m Q&A

*Bonus: describe a potential goal for NEAR at this event.*
Grow ecosystem, connect with speakers and attendees to attract them into your ecosystem. Will receive emails of all attendees that didn't opt-out.

**Additional Context**
Website: https://defi-fullstack.dystopialabs.com/
Current major sponsors: other layer1s. 
Focusing on useful talk that provide value vs just presenting projects.

**Comment by ashleynear** [comment]
Requesting $ for a speaking slot only. 

Closing issue, will not fix.
