### ISSUE TITLE
[May 28] [Online] Panel at Diffusion Digital

### ISSUE THREAD

**Issue by ilblackdragon** [nearprotocol/near-events#28]
**What is the event?**
Panel at Diffusion conference.

**Where is the event?**
Online

**When is the event?**
10:45-11:15am (GMT) Thurs 28th May

**Who are the attendees and how many are expected?**
Not sure, we should check.

**Describe how you'd like NEAR to ideally participate**
![image](https://user-images.githubusercontent.com/175486/82694867-e4344380-9c18-11ea-97e4-349b0556a275.png)

**Additional Context**
https://diffusion.events

**Contact**
Email with Outlier Ventures team

**Comment by ashleynear** [comment]
Done, view trello for more info
