### ISSUE TITLE
Berlin Developer Conference on the 4th of April

### ISSUE THREAD

**Issue by AnaisUrlichs** [nearprotocol/near-events#3]
**What is the event?**

From the organiser
The rationale: While we all agree that there's monstrous potential in decentralized ledger technologies, I frequently meet "traditional" developers who might even never have read a primer on why a trustful, decentralized, transactional, commonly shared storage backend is uber-useful. We'd like to change that by inviting software developers of all trades to join us in one full day of workshops ranging from beginner level up to a deep dive into certain (your) applications of ledger technologies. The goal is to enable many more developers to understand why "decentralized" matters in this decade and how to approach it.

Since a workshop day without workshops is boring and food options & quality depends on fiat budget (we might also accept crypto, but only tradeable coins!), I'd kindly like to ask you here and now if you'd like to contribute. :) Here are some possibilities: 
- present a workshop on your technology (or a general topic) 
- Become a sponsor (we'll call you "friends with benefits") who contributes to paying for food, space, wifi. Saves you a space on all printed and digital marketing material (contributions from €1000, only used to cover all expenses) 
- officially be there, look good, wear a funny branded t-shirt, evangelize people 
- spread the news over your favorite (de)centralized marketing channels Bonus: we're of course looking for the one and only "getting started with Blockchain" session that opens the door to the rabbit hole and everybody would like to attend (I'm thinking, this should be done in Bitcoin or Ethereum but I'm opionated). If you'd like to present that, just tell us :) 

Here are the workshop submission guidelines: 
- This is for developers Developers don't care for crypto economy in the first place (but Defi is certainly cool! An "ICO in 2020 / DAOs are the new Incs." also sounds legit) 
- Tell developers what your tech does and why (you think) it's better than using replicated MySQL.
- Be prepared to explain some things from 0x0 (or N, for the ternaries) 
- Get into the details. You'll never get people closer to yarn install your cli binary or adding the browser extension than in a workshop scenario. 
- Interactive parts are hard to do but fun to attend. 
- After 2 hours you should come to an end

The event will be free to all participants. 

**When is the event?**
"The Ledger" workshop day on April 4, 2020 in Berlin 

**Describe how you'd like NEAR to ideally participate**
Provide a workshop to participants, sponsor the event, reach non-crypto dev; easier onboarding since they still do not have pre-existing blockchain schemas.

**Describe alternatives you'd be open to**
/ 

**Describe what the goal of the event is**
Berlin has one of the largest crypto communities in the world. However, on most events, other Layer 1 solutions are quite present and it is difficult to get the attention of new developers (for a 2h workshop). The goal is to reach new developers, receive dev feedback, host a guided workshop that might motivate participants to dig further, and ultimately, get developers to try NEAR and become part of the contributor program.

**Additional Context**
Could be hosted in addition to a NEAR event with our investors (Greenfield) and the zk summit in Berlin on the 31st of March.

**Contact**
Discord, Slack, Commonwealth, Telegram :D 

**Timeline** 
Need to respond within the next 2 weeks.

**Comment by ashleynear** [comment]
@AnaisUrlichs how many attendees are they expecting? (note-- add this to the template)

Can we do a workshop without any financial contribution?

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #3: Berlin Developer Conference on the 4th of April](https://trello.com/c/nzoMaAi0/8-issue-3-berlin-developer-conference-on-the-4th-of-april)

**Comment by AnaisUrlichs** [comment]
I have asked, they expect around 60 to 90. It would seem a bit rude not to contribute financially; maybe we can negotiate token/fiat value.

Also, Flux would like to host a small 25 people hackathon to "test" the interest in the area. We could combine this event with the hackathon and maybe a third speaker-focused event in Berlin.

**Comment by ashleynear** [comment]
After some quick math:

60-90 people
Will require around 2k in spend with travel.

We need to convert 1% of all attendees, at a cost of 2K per dev.

I'm not sure that wee can reasonably expect that with such a small attendance? Idk, I could easily be wrong.


Also, since there is no webpage on this event anywhere other than meetup, it's making it harder to evaluate.

**Comment by ashleynear** [comment]
> For context in considering the event

**What is the event?**
Berlin Developer Conference | No webpage

**Who is the event for?**
Software developers of all trades ; 60-90 developers total

**When is the event starting?**
April 4th, 2020

**How is the event structured?**
It could be one workshop hosted by NEAR that is part of a full day of workshops.

**What type of event is this?**: 
speak, sponsor, teach a workshop

**How much would it cost?**
1000 EUR + At least another 500- 1K USD in travel and lodging. 

**What are our goals?**
 - More developers building on NEAR
 - Education; both in the sense of educating others on NEAR, while gaining feedback for our Education
- Awareness; getting more people to be aware of NEAR.


**How much is a base ticket for an attendee?**

Free? Unsure, there's no webpage for the event. 

**Have we attended before?**
No.

**Comment by ashleynear** [comment]
@AnaisUrlichs do you know if we will have all information of attendees at least one week prior?

**Comment by ashleynear** [comment]
### NEAR wants to do this event as an ongoing part of our effort to establish a community baseline presence in Europe. 

### We believe we can accomplish this with one person (Anais) attending and being an evangelist of NEAR and becoming part of of on the ground presence in Europe.

**Comment by bowenwang1996** [comment]
@dcodeIO would this be interesting to you?

**Comment by ashleynear** [comment]
@alexbrienes @eriktrautman any thoughts here? Seemed inconclusive from today's meeting

**Comment by ashleynear** [comment]
@AnaisUrlichs We've decided to send you with some swag to hustle but are not going to formally participate in the event due to limited workshop resources/ return on the amount of attendees. However, we are happy to send you with swag, let me know if this is going to work for you!

**Comment by AnaisUrlichs** [comment]
Sounds great :)

**Comment by ashleynear** [comment]
https://trello.com/c/nzoMaAi0 <--- to see the progress of actions to take before this event, view this card.
