### ISSUE TITLE
San Francisco DeFi Hackathon 

### ISSUE THREAD

**Issue by NikitaMarin** [nearprotocol/near-events#5]
**What is the event?**

DeFi and Interoperability Hackathon Feb 29 - March 1, 2020, at the Hack temple (906.worlds) in San Francisco.

Eventbrite: bit.ly/SF_DeFi_Hackathon
Twitter: twitter.com/DeFi_Hackathon
Sponsorship deck: bit.ly/DefiHackathon

**When is the event?**

Feb 29 - March 1, 2020,

**Who are the attendees and how many are expected?**

368 developers have registered to that date. The first 300 registration was free. 68 sold tickets. We are expecting around 200 participating developers.

The Judges and mentors:
Pavel Cherkashin, Managing Partner at Mindrock Capital and GVA Capital
Luke Kim, Berkeley Blockchain Xcelerator
Adam Leon, MouseBelt Blockchain AcceleratorJesus Flores, Rangel Principal at Hack Fund
Sean Hoge, Managing Partner at Genesis Block Joshua Armah, CTO Snowball MoneySteve Wei, Co-founder & CEO at TOP Network Alexander Meyer, Co-founder 360 Lab San Francisco

**Describe how you'd like NEAR to ideally participate**

We’d be honored to invite the Near protocol to sponsor challenges for developers and/or to be presented with the workshop.

**Describe alternatives you'd be open to**
We’d be honored to invite the Near protocol as co-host of the Hackathon

**Describe what the goal of the event is**

The potential goal for NEAR at this event:
ECOSYSTEM ENHANCEMENT 
TESTING OF TECHNOLOGY
DEVELOPER ENGAGEMENT
INNOVATION
RECRUITMENT
CORPORATE BRANDING

**Additional Context**

The voting process at the Hackathon is powered by Aragon and UniDAO. Aragon will support us with media coverage as well.

Every participant, winner, judge and mentor at World Blockchain Hackathon SF will receive personal blockchain based certificate provided by Credentia. Digital certificates are W3C Verifiable Credentials compliant and Ethereum-based credentials certifying participation in the World Blockchain Hackathon SF.
https://medium.com/@sgershuni/828503bba41c

**Contact**
+14243244408
marin.nikita@gmail.com

**Comment by ashleynear** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #5: San Francisco DeFi Hackathon ](https://trello.com/c/Pz39zegB/5-issue-5-san-francisco-defi-hackathon)

**Comment by ashleynear** [comment]
@NikitaMarin we've evaluated this and realized it's not enough time for us to go ahead and move forward with this. Thank you for reaching out; please feel free to submit future events here as well :). Typically 3-4 weeks lead up before a hackathon is our ideal timeframe!
