### ISSUE TITLE
ETHCC March 3-5th

### ISSUE THREAD

**Issue by ashleynear** [nearprotocol/near-events#7]
**What is the event?**
https://ethcc.io/ | The Ethereum Community Conference (EthCC) is the largest annual European Ethereum event focused on technology and community. Three intense days of conferences, networking and learning.

**When is the event?**
March 3-5th

**Who are the attendees and how many are expected?**
EthCC is the largest blockchain conference after Devcon with more that 1,500 Participants and 250 speakers but also the cheapest (300€, free for students and volunteers)

**Describe how you'd like NEAR to ideally participate**
Sponsor | We have multiple business clients coming during the "France Blockchain Week" for side events (30 last year)

**Describe alternatives you'd be open to**
Attend!

**Describe what the goal of the event is**
Inform the large community of ETH devs about NEAR

*Bonus: describe a potential goal for NEAR at this event.*

**Additional Context**
Add any other context, or pitch decks, websites, proposals, ect, about the event here.
[EthCC-sponsor deck 2020.pdf](https://github.com/nearprotocol/near-events/files/4246391/EthCC-sponsor.deck.2020.pdf)

**Contact**
sponsors@ethcc.io

**Comment by eriktrautman** [comment]
Demonstrating @ashleynear @AnaisUrlichs  tagging

**Comment by ashleynear** [comment]
> Quick context for consideration of the event

**What is the event?**
https://ethcc.io/ | The Ethereum Community Conference (EthCC) is the largest annual European Ethereum event focused on technology and community. Three intense days of conferences, networking and learning.


**When is the event?**
March 3-5th

**Who are the attendees and how many are expected?**
EthCC is the largest blockchain conference after Devcon with more that 1,500 Participants and 250 speakers but also the cheapest (300€, free for students and volunteers)

**How is it structured**
 It is a conference 

**Type of Event**
Attend


**How much would it cost?**
$300 EU per attendee + minimum 500 for travel & lodging (1 person, based in EU already)

**Goals**
- hustle the event and establish a baseline for a hustle only event
- use this as part of our strategy to have an events presence in EU

**Base Ticket Cost**

300 EU

**Have we attended before?**
Kendall went last year: ```Went last year. Definitely worth sending 1-2 people to mingle, as attracts a quality crowd```

**Comment by ashleynear** [comment]
### NEAR wants to do this event to establish our pipeline baselines for a hustle only/ attending only event.

### We believe we can accomplish this based on the past attendance from a team member validating the quality of the crowd, and based on the amount of people who attend (1500+).

**Comment by ashleynear** [comment]
@eriktrautman @AnaisUrlichs Would at least one of y'all be able to attend this one?

**Comment by ashleynear** [comment]
Closing based on inactivity.
